server:
  port: 8200
  servlet:
    context-path: /ad-export
spring:
  application:
    name: ad-export-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ad_data?serverTimezone=Asia/Shanghai
    username: root
    password: Yy3295690
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
