spring:
  application:
    name: ad-eureka

server:
  port: 6000

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: eureka0
server:
  port: 6000
eureka:
  instance:
    hostname: peer0
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://peer1:6001/eureka/, http://peer2:6002/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: eureka1
server:
  port: 6001
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://peer0:6000/eureka/, http://peer2:6002/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: eureka2
server:
  port: 6002
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://peer0:6000/eureka/, http://peer1:6001/eureka/
