spring:
  application:
    name: ad-gateway
server:
  port: 7000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/eureka/

zuul:
  prefix: /
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: ad-sponsor-service
      strip-prefix: false
    search:
      path: /ad-search/**
      serviceId: ad-search-service
      strip-prefix: false