server:
  port: 8000
  servlet:
    context-path: /ad-sponsor
spring:
  application:
    name: ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ad_data?serverTimezone=Asia/Shanghai
    username: root
    password: Yy3295690
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/eureka/
